import type { NewsItem, TickerItem } from "./types"

export const mockNewsData: NewsItem[] = [
  {
    id: "mock-1",
    ticker: "AAPL",
    companyName: "Apple Inc.",
    title: "Apple announces new AI-powered features coming to iPhone, boosting investor confidence in the tech giant's AI strategy.",
    summary: "Apple is set to revolutionize the iPhone experience with cutting-edge AI features that leverage on-device machine learning.",
    source: "Bloomberg",
    time: "2 min ago",
    url: "#",
    imageUrl: "",
    sentiment: "bullish",
    sentimentScore: 0.82,
    priceChange: 2.34,
    currentPrice: 198.50,
    sparklineData: [142, 145, 143, 148, 150, 149, 153, 155, 154, 158],
    category: "technology",
  },
  {
    id: "mock-2",
    ticker: "TSLA",
    companyName: "Tesla Inc.",
    title: "Tesla's Q4 deliveries miss expectations as competition in the EV market intensifies significantly across global markets.",
    summary: "Tesla delivered fewer vehicles than analysts expected in Q4, signaling increased competitive pressure in the electric vehicle space.",
    source: "Reuters",
    time: "15 min ago",
    url: "#",
    imageUrl: "",
    sentiment: "bearish",
    sentimentScore: 0.71,
    priceChange: -3.12,
    currentPrice: 240.30,
    sparklineData: [265, 260, 258, 255, 252, 248, 250, 245, 243, 240],
    category: "technology",
  },
  {
    id: "mock-3",
    ticker: "NVDA",
    companyName: "NVIDIA Corp.",
    title: "NVIDIA dominates AI chip market with 80% share, new Blackwell architecture exceeds all performance expectations.",
    summary: "NVIDIA's Blackwell GPU architecture sets new benchmarks in AI training performance, further solidifying the company's market leadership.",
    source: "TechCrunch",
    time: "32 min ago",
    url: "#",
    imageUrl: "",
    sentiment: "bullish",
    sentimentScore: 0.91,
    priceChange: 5.22,
    currentPrice: 768.00,
    sparklineData: [720, 725, 730, 728, 740, 745, 750, 755, 760, 768],
    category: "technology",
  },
  {
    id: "mock-4",
    ticker: "JPM",
    companyName: "JPMorgan Chase",
    title: "JPMorgan reports record trading revenue amid global market volatility and rising interest rate environment.",
    summary: "JPMorgan's trading desk delivered record revenues as market volatility created opportunities for the banking giant.",
    source: "Financial Times",
    time: "1 hr ago",
    url: "#",
    imageUrl: "",
    sentiment: "bullish",
    sentimentScore: 0.75,
    priceChange: 1.87,
    currentPrice: 193.00,
    sparklineData: [180, 182, 181, 185, 186, 188, 187, 190, 191, 193],
    category: "finance",
  },
  {
    id: "mock-5",
    ticker: "XOM",
    companyName: "Exxon Mobil",
    title: "Oil prices drop as OPEC+ signals potential increase in production quotas for the coming quarter ahead of schedule.",
    summary: "OPEC+ members are reportedly considering boosting oil production quotas, putting downward pressure on crude prices.",
    source: "CNBC",
    time: "2 hr ago",
    url: "#",
    imageUrl: "",
    sentiment: "bearish",
    sentimentScore: 0.65,
    priceChange: -1.45,
    currentPrice: 95.00,
    sparklineData: [105, 103, 104, 101, 100, 98, 99, 97, 96, 95],
    category: "energy",
  },
  {
    id: "mock-6",
    ticker: "MSFT",
    companyName: "Microsoft Corp.",
    title: "Microsoft's Azure cloud revenue grows 29% YoY as enterprise AI adoption accelerates rapidly across industries.",
    summary: "Microsoft reported strong Azure growth driven by increasing enterprise demand for AI and cloud computing services.",
    source: "The Verge",
    time: "3 hr ago",
    url: "#",
    imageUrl: "",
    sentiment: "bullish",
    sentimentScore: 0.88,
    priceChange: 3.15,
    currentPrice: 435.00,
    sparklineData: [410, 412, 415, 418, 420, 422, 425, 428, 430, 435],
    category: "technology",
  },
  {
    id: "mock-7",
    ticker: "PFE",
    companyName: "Pfizer Inc.",
    title: "Pfizer's new oncology drug shows promising Phase 3 trial results, marking a potential blockbuster drug in the pipeline.",
    summary: "Pfizer's experimental oncology treatment demonstrated statistically significant efficacy in late-stage clinical trials.",
    source: "MedPage Today",
    time: "4 hr ago",
    url: "#",
    imageUrl: "",
    sentiment: "bullish",
    sentimentScore: 0.79,
    priceChange: 4.10,
    currentPrice: 36.00,
    sparklineData: [28, 29, 30, 29, 31, 32, 33, 34, 35, 36],
    category: "healthcare",
  },
  {
    id: "mock-8",
    ticker: "META",
    companyName: "Meta Platforms",
    title: "Meta faces regulatory headwinds in the EU as new digital markets act enforcement deadline approaches in March.",
    summary: "The European Union is preparing to enforce strict new rules under the Digital Markets Act, potentially impacting Meta's business model.",
    source: "Wall Street Journal",
    time: "5 hr ago",
    url: "#",
    imageUrl: "",
    sentiment: "bearish",
    sentimentScore: 0.62,
    priceChange: -2.08,
    currentPrice: 498.00,
    sparklineData: [520, 518, 515, 512, 510, 508, 505, 503, 500, 498],
    category: "technology",
  },
  {
    id: "mock-9",
    ticker: "GS",
    companyName: "Goldman Sachs",
    title: "Goldman Sachs upgrades 2026 market outlook, sees S&P 500 hitting new highs driven by strong corporate earnings.",
    summary: "Goldman Sachs strategists raised their year-end S&P 500 target, citing robust earnings growth and continued economic resilience.",
    source: "MarketWatch",
    time: "6 hr ago",
    url: "#",
    imageUrl: "",
    sentiment: "bullish",
    sentimentScore: 0.72,
    priceChange: 1.55,
    currentPrice: 400.00,
    sparklineData: [380, 382, 385, 384, 388, 390, 392, 395, 397, 400],
    category: "finance",
  },
]

export const mockTickerData: TickerItem[] = [
  { symbol: "AAPL", name: "Apple Inc.", price: 198.50, change: 4.63, changePercent: 2.34 },
  { symbol: "TSLA", name: "Tesla Inc.", price: 240.30, change: -7.73, changePercent: -3.12 },
  { symbol: "NVDA", name: "NVIDIA Corp.", price: 768.00, change: 38.10, changePercent: 5.22 },
  { symbol: "MSFT", name: "Microsoft Corp.", price: 435.00, change: 13.28, changePercent: 3.15 },
  { symbol: "META", name: "Meta Platforms", price: 498.00, change: -10.58, changePercent: -2.08 },
  { symbol: "JPM", name: "JPMorgan Chase", price: 193.00, change: 3.54, changePercent: 1.87 },
  { symbol: "GS", name: "Goldman Sachs", price: 400.00, change: 6.10, changePercent: 1.55 },
  { symbol: "XOM", name: "Exxon Mobil", price: 95.00, change: -1.40, changePercent: -1.45 },
]
